// Code generated by tygo. DO NOT EDIT.

//////////
// source: types.go

export type RoomID = string;
export type PlayerID = string;
export type Card = number /* int */;
export type Pile = Card[];
export type Hand = Card[];
export type DiscardPiles = Pile[];
export type BuildPiles = Pile[];
export const ServerMessageTypeError = "error";
export const ServerMessageTypeRoomState = "room.state";
export const ServerMessageTypeGameState = "game.state";
export type ServerMessageType = typeof ServerMessageTypeError | typeof ServerMessageTypeRoomState | typeof ServerMessageTypeGameState;
export interface ServerMessage {
  type: ServerMessageType;
  payload: unknown /* json.RawMessage */;
}
export const ClientMessageTypeLobbyStart = "lobby.start";
export const ClientMessageTypeGamePlayFromHand = "game.playFromHand";
export const ClientMessageTypeGamePlayFromStock = "game.playFromStock";
export const ClientMessageTypeGamePlayFromDiscard = "game.playFromDiscard";
export const ClientMessageTypeGameDiscard = "game.discard";
export type ClientMessageType = typeof ClientMessageTypeLobbyStart | typeof ClientMessageTypeGamePlayFromHand | typeof ClientMessageTypeGamePlayFromStock | typeof ClientMessageTypeGamePlayFromDiscard | typeof ClientMessageTypeGameDiscard;
export interface ClientMessage {
  type: ClientMessageType;
  payload: unknown /* json.RawMessage */;
}
export interface GameView {
  isPlayerTurn: boolean;
  buildPiles: BuildPiles;
  discardPiles: DiscardPiles;
  hand: Hand;
  stockPileCount: number /* int */;
  stockPileTopCard: Card;
  opponnents: Opponent[];
}
export interface RoomView {
  roomId: RoomID;
  isHost: boolean;
  id: PlayerID;
  players: PlayerView[];
}
export interface PlayerView {
  id: PlayerID;
  score: number /* int */;
  connected: boolean;
}
export interface Opponent {
  playerId: PlayerID;
  handCount: number /* int */;
  stockPileCount: number /* int */;
  stockPileCard: Card;
  discardPiles: DiscardPiles;
}
export interface PlayFromDiscardPayload {
  discardPileIdx: number /* int */;
  buildPileIdx: number /* int */;
}
export interface PlayFromStockPayload {
  buildPileIdx: number /* int */;
}
export interface PlayFromHandPayload {
  cardIdx: number /* int */;
  buildPileIdx: number /* int */;
}
export interface DiscardPayload {
  cardIdx: number /* int */;
  discardPileIdx: number /* int */;
}
export type ErrorPayload = string;
